database:
  plan: free
  database_name: insait_security_db
  instance_class: free

build:
  commands:
    - pip install -r requirements.txt
    - cd securitywebpage && python manage.py migrate && python manage.py seed_data
  publish: "securitywebpage"

services:
  - type: web
    name: insait-security-webpage
    plan: free
    branch: main
    region: frankfurt
    startCommand: cd securitywebpage && python manage.py migrate && python manage.py seed_data && cd .. && gunicorn insait_security_group_webpage.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: insait_security_group_webpage.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
