# Generated by Django 6.0.4 on 2026-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('phd', 'PhD Candidates'), ('visitors', 'Visitors & Collaborators')], default='phd', max_length=20),
        ),
    ]
